export default {
    date:{
      year:{
        title:'年',
        value:1902
      },
      month:{
        title:'月',
        value:[1,12]
      },
      day:{
        title:'日',
        value:1
      },
      hour:{
        title:'时',
        value:[0,23]
      },
      minute:{
        title:'分',
        value:[0,59]
      },
      pov:{
        title:'省'
      },
      city:{
        title:'城市'
      }
    },
    tips:{
      errCode:{
        400:'参数错误',
        403:'权限受限，请联系管理员',
        404:'请求链接不存在,请联系管理员',
        405:'请求方式不正确,应为POST/GET',
        500:'服务器错误,请联系管理员',
        default:'无效的请求,状态码($),请联系管理员',
        other:'未知错误，请联系管理排查'
      }
    },
    host:'',
    wxinterface:[
      'startRecord',
      'stopRecord',
      'onVoiceRecordEnd',
      'playVoice',
      'pauseVoice',
      'stopVoice',
      'onVoicePlayEnd',
      'uploadVoice',
      'downloadVoice',
      'chooseImage',
      'previewImage',
      'uploadImage',
      'downloadImage',
      'translateVoice',
      'getNetworkType',
      'openLocation',
      'getLocation',
      'hideOptionMenu',
      'showOptionMenu',
      'hideMenuItems',
      'showMenuItems',
      'hideAllNonBaseMenuItem',
      'showAllNonBaseMenuItem',
      'closeWindow',
      'scanQRCode',
      'chooseWXPay',
      'openProductSpecificView',
      'addCard',
      'chooseCard',
      'openCard',
      'updateAppMessageShareData',
      'onMenuShareAppMessage',
      'onMenuShareTimeline',
      'updateTimelineShareData',
  ]

}